# fly.toml app configuration file generated for walk-article-backend on 2026-07-19T01:54:14+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'walk-article-backend'
primary_region = 'nrt'

[build]
[processes]
  api = 'node dist/server.js'
  retention = 'node dist/workers/audioRetention.worker.js'
  worker = 'node dist/workers/transcribeAndGenerate.worker.js'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['api']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
  processes = ['api', 'worker', 'retention']
